name: Build & Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    - name: Build release APK
      run: |
        cd frontend
        flutter build apk --release

    - name: Zip source code
      run: |
        zip -r source.zip frontend -x "**/build/**" "**/.dart_tool/**" "**/.git/**" "**/.idea/**"

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v1.0.${{ github.run_number }}"
        name: Release v1.0.${{ github.run_number }}
        files: |
          frontend/build/app/outputs/flutter-apk/app-release.apk
          source.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Bump version and push tag
      id: bump-version
      uses: phips28/gh-action-bump-version@v9.0.3
      with:
        commit-message: "ci: bump version to {{version}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
